version: "2"
services:
  server:
    build: ./server
    container_name: tic-server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/server

  client:
    build: ./client
    container_name: tic-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    network_mode: "host"
